### ISSUE TITLE
Upgrade to laravel 5.4

### ISSUE THREAD

**Issue by GitzJoey** [GitzJoey/TKBARUPHP#161]
1. make sure new installation still working
2. converting gulp into laravel mix
3. possibility to change entrust to other package that support 5.4 (laratrust)
4. change php into version 7

**Comment by Arsfiqball** [comment]
What about axios? should we add it too and remove vue-resource?

**Comment by GitzJoey** [comment]
I haven't see any major needs using axios, but i'm open for any PR of axios

**Comment by Arsfiqball** [comment]
ok, working on it
