### ISSUE TITLE
VueJS Compatibility

### ISSUE THREAD

**Issue by GitzJoey** [GitzJoey/TKBARUPHP#177]
Jquery Component
1. ParsleyJS
2. DateTimePicker
3. Select2

Solution can be replacing it or make a wrapper component for it

**Comment by Arsfiqball** [comment]
@GitzJoey I hate to do a silly messy hacky way...
The existing code looks weird (for me) and seems unorganized well.
Or myself is too much idealist.
I built a new design for authentication (login, register, emails, reset) that uses validation similar way parsley does. But different technique, I code it myself with help from VeeValidate in vue component.
here is the experimental branch: https://github.com/Arsfiqball/TKBARUPHP/tree/cleanup-auth-view
