### ISSUE TITLE
Module needs to be Vue'd

### ISSUE THREAD

**Issue by GitzJoey** [GitzJoey/TKBARUPHP#183]
* ~~Phone Provider~~
* ~~Unit~~
* Today Price
* ~~Truck~~
* ~~Currencies~~
* ~~Vendor Trucking~~
* Accounting - CashAccount + CashFlow
* Accounting - Capital
* Accounting - Expense
* Accounting - Revenue
* ~~Price Level~~
* ~~Giro~~
* ~~Truck Maintenance~~
* ~~Employee~~
* ~~Product Type~~
* ~~Bank~~
* ~~Expense Template~~
* ~~User~~
* ~~Role~~

**Comment by sandisahdewo** [comment]
Issues closed 
1. Unit
2. Truck
3. Currencies
4. Giro
5. Truck Maintenance
6. Product Type
7. Role
8. Vendor Trucking
9. Expense Template
10. Bank
11. Employee
12. User
